# TODO: explain it
name: my_first_site

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: my_first_site
meta_keywords: "some meta keywords"
meta_description: "some meta description"